// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Greeting             string   `protobuf:"bytes,2,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloRequest) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

// The response message containing the greetings.
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DelayedReply struct {
	Message              string          `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Request              []*HelloRequest `protobuf:"bytes,2,rep,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *DelayedReply) Reset()         { *m = DelayedReply{} }
func (m *DelayedReply) String() string { return proto.CompactTextString(m) }
func (*DelayedReply) ProtoMessage()    {}
func (*DelayedReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *DelayedReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DelayedReply.Unmarshal(m, b)
}
func (m *DelayedReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DelayedReply.Marshal(b, m, deterministic)
}
func (m *DelayedReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DelayedReply.Merge(m, src)
}
func (m *DelayedReply) XXX_Size() int {
	return xxx_messageInfo_DelayedReply.Size(m)
}
func (m *DelayedReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DelayedReply.DiscardUnknown(m)
}

var xxx_messageInfo_DelayedReply proto.InternalMessageInfo

func (m *DelayedReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DelayedReply) GetRequest() []*HelloRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "test.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "test.HelloReply")
	proto.RegisterType((*DelayedReply)(nil), "test.DelayedReply")
}

func init() {
	proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e)
}

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xec, 0xb8, 0x78, 0x3c, 0x52,
	0x73, 0x72, 0xf2, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12,
	0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x29, 0x2e, 0x8e, 0xf4,
	0xa2, 0xd4, 0xd4, 0x92, 0xcc, 0xbc, 0x74, 0x09, 0x26, 0xb0, 0x38, 0x9c, 0xaf, 0xa4, 0xc6, 0xc5,
	0x05, 0xd5, 0x5f, 0x90, 0x53, 0x29, 0x24, 0xc1, 0xc5, 0x9e, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x0e,
	0x33, 0x00, 0xc6, 0x55, 0x0a, 0xe3, 0xe2, 0x71, 0x49, 0xcd, 0x49, 0xac, 0x4c, 0x4d, 0x21, 0xa0,
	0x52, 0x48, 0x87, 0x8b, 0xbd, 0x08, 0xe2, 0x18, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x6e, 0x23, 0x21,
	0x3d, 0xb0, 0xab, 0x91, 0x9d, 0x19, 0x04, 0x53, 0x62, 0xf4, 0x85, 0x91, 0x8b, 0x25, 0x04, 0xe4,
	0x70, 0x03, 0x2e, 0x8e, 0xe0, 0xc4, 0x4a, 0xb0, 0x22, 0x21, 0x2c, 0x3a, 0xa4, 0x04, 0x50, 0xc4,
	0x40, 0x4e, 0xb0, 0xe4, 0xe2, 0x0f, 0x48, 0x2c, 0x2a, 0xca, 0x2f, 0x09, 0x4e, 0xac, 0x2c, 0x26,
	0x41, 0xa3, 0x01, 0xa3, 0x90, 0x23, 0x97, 0xa8, 0x73, 0x46, 0x62, 0x49, 0x49, 0xa5, 0x73, 0x4e,
	0x66, 0x6a, 0x1e, 0x01, 0x03, 0xa0, 0x62, 0xc8, 0xde, 0xd7, 0x60, 0x14, 0xb2, 0xe1, 0x12, 0xf0,
	0xcc, 0x2b, 0x49, 0x2d, 0x4a, 0x4c, 0x06, 0x85, 0x23, 0x09, 0xd6, 0x6b, 0x30, 0x1a, 0x30, 0x3a,
	0xb1, 0x47, 0xb1, 0xea, 0x27, 0xe7, 0x17, 0xa5, 0x26, 0xb1, 0x81, 0x23, 0xd3, 0x18, 0x10, 0x00,
	0x00, 0xff, 0xff, 0x06, 0xed, 0x00, 0xdd, 0xda, 0x01, 0x00, 0x00,
}
